"use client";
import {useState} from "react";
import {useQuery,useQueryClient} from "@tanstack/react-query";
import {useTranslations} from "next-intl";
import {api} from "@/lib/api/client";
import {useCan} from "@/lib/api/hooks";
import {Button} from "@/components/ui/button";

export function ReportTools({workspaceId,filter}:{workspaceId:string;filter:string}){
  const t=useTranslations("engagement"),client=useQueryClient();const canExport=useCan("data:export");const [row,setRow]=useState("channel"),[column,setColumn]=useState("sentiment"),[value,setValue]=useState("count");const [emails,setEmails]=useState("");const [cadence,setCadence]=useState("week");const [error,setError]=useState("");
  const pivot=useQuery({queryKey:["pivot",filter,row,column,value],queryFn:()=>api<{row:string;column:string;value:number|null}[]>(`/analytics/pivot?${filter}&row=${row}&column=${column}&value=${value}`)});
  const questions=useQuery({queryKey:["per-question",filter],queryFn:()=>api<{survey_id:string;code:string;title:Record<string,string>;answered:number;average?:number;nps?:number}[]>(`/analytics/per-question?${filter}`)});
  const schedules=useQuery({queryKey:["schedules",workspaceId],enabled:canExport,queryFn:()=>api<{id:string;recipients:string[];cadence:string;enabled:boolean}[]>(`/report-schedules?workspace_id=${workspaceId}`)});
  async function schedule(){try{await api("/report-schedules",{method:"POST",body:{workspace_id:workspaceId,recipients:emails.split(/[\s,;]+/).filter(Boolean),cadence,next_run_at:new Date(Date.now()+60000).toISOString(),filters:Object.fromEntries(new URLSearchParams(filter))}});await client.invalidateQueries({queryKey:["schedules"]});}catch(e){setError((e as Error).message);}}
  return <div className="space-y-5"><section className="space-y-3 rounded-xl border bg-card p-5"><h2 className="text-xl font-semibold">{t("perQuestion")}</h2>{questions.data?.map(q=><p key={`${q.survey_id}:${q.code}`}>{q.title.vi}: {t("answered",{count:q.answered})}{q.average!=null&&` · ${t("average")}: ${q.average.toFixed(2)}`}{q.nps!=null&&` · NPS: ${q.nps.toFixed(1)}`}</p>)}</section>
    <section className="space-y-3 rounded-xl border bg-card p-5"><h2 className="text-xl font-semibold">{t("pivot")}</h2><div className="flex flex-wrap gap-3">{[[row,setRow,"row"],[column,setColumn,"column"]].map(([selected,setter,label])=><label key={String(label)}>{t(String(label))}<select className="ml-2 rounded border p-2" value={String(selected)} onChange={e=>(setter as (v:string)=>void)(e.target.value)}>{["channel","survey","branch","sentiment"].map(d=><option key={d} value={d}>{t(`dimensions.${d}`)}</option>)}</select></label>)}<label>{t("value")}<select className="ml-2 rounded border p-2" value={value} onChange={e=>setValue(e.target.value)}>{["count","rating","csat"].map(d=><option key={d} value={d}>{t(`values.${d}`)}</option>)}</select></label></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr><th>{t("row")}</th><th>{t("column")}</th><th>{t("value")}</th></tr></thead><tbody>{pivot.data?.map((cell,i)=><tr key={i}><td className="p-2">{cell.row}</td><td className="p-2">{cell.column}</td><td className="p-2">{cell.value?.toFixed(value==="count"?0:2)??"—"}</td></tr>)}</tbody></table></div></section>
    {canExport&&<section className="space-y-3 rounded-xl border bg-card p-5"><h2 className="text-xl font-semibold">{t("schedule")}</h2><label className="block">{t("emails")}<textarea className="block w-full rounded border p-2" value={emails} onChange={e=>setEmails(e.target.value)}/></label><select aria-label={t("cadence")} className="rounded border p-2" value={cadence} onChange={e=>setCadence(e.target.value)}>{["day","week","month"].map(c=><option key={c} value={c}>{t(`cadences.${c}`)}</option>)}</select><Button className="ml-3" onClick={()=>{void schedule();}}>{t("createSchedule")}</Button>{error&&<p role="alert">{error}</p>}{schedules.data?.filter(s=>s.enabled).map(s=><div key={s.id} className="flex flex-wrap gap-3"><p>{s.recipients.join(", ")} · {t(`cadences.${s.cadence}`)}</p><Button variant="outline" onClick={async()=>{try{await api(`/report-schedules/${s.id}`,{method:"DELETE"});await client.invalidateQueries({queryKey:["schedules"]});}catch(e){setError((e as Error).message);}}}>{t("stopSchedule")}</Button></div>)}</section>}
  </div>;
}
